app/routes/post.py
from flask import Blueprint, render_template, request, redirect, abort
from flask_login import login_required, current_user
from sqlalchemy import desc

from ..extensions import db
from ..forms import StudentForm, TeacherForm
from ..models.models import Post, User, Role

post = Blueprint("post", __name__)
@post.route("/", methods=["POST", "GET"])
def all():
    form = TeacherForm()
    # Выбираем пользователей с ролью "teacher"
    teacher_role = Role.query.filter_by(name='teacher').first()
    if not teacher_role:
        abort(500, "Role 'teacher' not found in the database.")
    form.teacher.choices = [t.name for t in User.query.filter_by(role_id=teacher_role.id).all()]

    if request.method == "POST":
        teacher = request.form["teacher"]
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template("post/all.html", posts=posts, user=User, form=form)


@post.route("/post/create", methods=["POST", "GET"])
@login_required
def create():
    form = StudentForm()
    # Выбираем пользователей с ролью "student"
    student_role = Role.query.filter_by(name='student').first()
    if not student_role:
        abort(500, "Role 'student' not found in the database.")
    form.student.choices = [s.name for s in User.query.filter_by(role_id=student_role.id).all()]

    if request.method == "POST":
        subject = request.form.get("subject")
        student = request.form.get("student")
        student_id = User.query.filter_by(name=student).first().id

        post = Post(teacher=current_user.id, subject=subject, student=student_id)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect("/")
        except Exception as e:
            db.session.rollback()
            print(str(e))

    return render_template("post/create.html", form=form)

@post.route("/post/<int:id>/update", methods=["POST", "GET"])
@login_required
def update(id):
    post = Post.query.get(id)

    # Проверяем, является ли пользователь автором поста или имеет роль "teacher"
    teacher_role = Role.query.filter_by(name='teacher').first()
    if post.author.id == current_user.id or current_user.role_id == teacher_role.id:
        form = StudentForm()
        student_role = Role.query.filter_by(name='student').first()
        if not student_role:
            abort(500, "Role 'student' not found in the database.")

        form.student.data = User.query.filter_by(id=post.student).first().name
        form.student.choices = [s.name for s in User.query.filter_by(role_id=student_role.id).all()]

        if request.method == "POST":
            post.subject = request.form.get("subject")
            student = request.form.get("student")

            post.student = User.query.filter_by(name=student).first().id

            try:
                db.session.commit()
                return redirect("/")
            except Exception as e:
                db.session.rollback()
                print(str(e))
        else:
            return render_template("post/update.html", post=post, form=form)
    else:
        abort(403)


@post.route("/post/<int:id>/delete", methods=["POST", "GET"])
@login_required
def delete(id):
    post = Post.query.get(id)

    # Проверяем, является ли пользователь автором поста или имеет роль "teacher"
    teacher_role = Role.query.filter_by(name='teacher').first()
    if post.author.id == current_user.id or current_user.role_id == teacher_role.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect("/")
        except Exception as e:
            db.session.rollback()
            print(str(e))
            return str(e)
    else:
        abort(403)

app/routes/user.py
from flask import Blueprint, redirect, render_template, flash, url_for, request
from flask_login import login_user, logout_user, login_required, current_user

from ..functions import save_picture
from ..forms import RegistrationForm, LoginForm, ProfileForm
from ..extensions import db, bcrypt
from ..models.models import User, Role


user = Blueprint("user", __name__)

@user.route("/profile/<int:user_id>", methods=["GET", "POST"])
@login_required
def profile(user_id):
    # Проверяем, что пользователь редактирует свой профиль
    if user_id != current_user.id:
        flash("У вас нет доступа к этому профилю.", "danger")
        return redirect(url_for("post.all"))

    form = ProfileForm()
    user = User.query.get_or_404(user_id)

    if request.method == "GET":
        # Заполняем форму текущими данными пользователя
        form.name.data = user.name
        form.login.data = user.login

    elif form.validate_on_submit():  # Обновляем только если форма валидна
        # Добавляем отладочные сообщения для проверки данных
        print(f"Данные из формы: name={form.name.data}, login={form.login.data}")

        # Обновляем поля пользователя
        user.name = form.name.data
        user.login = form.login.data

        if form.password.data:  # Если указан новый пароль
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            user.password = hashed_password

        if form.avatar.data:  # Если загружен новый аватар
            avatar_filename = save_picture(form.avatar.data)
            user.avatar = avatar_filename

        try:
            # Сохраняем изменения в базе данных
            db.session.commit()
            flash("Ваш профиль был успешно обновлен.", "success")
            return redirect(url_for("user.profile", user_id=user.id))
        except Exception as e:
            db.session.rollback()
            print(f"Ошибка при обновлении: {str(e)}")
            flash("Произошла ошибка при сохранении изменений. Попробуйте снова.", "danger")
    else:
        print(f"Ошибка валидации формы: {form.errors}")

    return render_template("user/profile.html", form=form, user=user)

@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_picture(form.avatar.data)

        # Получаем роль по умолчанию (например, "ученик"). Вы можете изменить это.
        default_role = Role.query.filter_by(name='student').first()

        if not default_role:
            flash("Ошибка регистрации: Роль по умолчанию не найдена. Обратитесь к администратору.", "danger")
            return redirect(url_for('user.register'))

        # Создаём нового пользователя с ролью
        user = User(
            name=form.name.data,
            login=form.login.data,
            avatar=avatar_filename,
            password=hashed_password,
            role_id=default_role.id,  # Присваиваем ID роли
            status='user'
        )
        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Поздравляем, {form.login.data}! Вы успешно зарегистрированы", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            db.session.rollback()
            print(str(e))
            flash(f"При регистрации произошла ошибка: {str(e)}", "danger")
    return render_template('user/register.html', form=form)


@user.route("/user/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            # Перенаправление в зависимости от роли
            if user.role.name == "admin":
                flash(f"Добро пожаловать, {form.login.data}! Вы вошли как администратор.", "success")
                return redirect(url_for("admin.dashboard"))
            elif user.role.name == "teacher":
                flash(f"Добро пожаловать, {form.login.data}! Вы вошли как учитель.", "success")
                return redirect(url_for("teacher.dashboard"))
            elif user.role.name == "student":
                flash(f"Добро пожаловать, {form.login.data}! Вы вошли как ученик.", "success")
                return redirect(url_for("student.dashboard"))
            elif user.role.name == "methodologist":
                flash(f"Добро пожаловать, {form.login.data}! Вы вошли как методист.", "success")
                return redirect(url_for("methodologist.dashboard"))
            elif user.role.name == "parent":
                flash(f"Добро пожаловать, {form.login.data}! Вы вошли как родитель.", "success")
                return redirect(url_for("parent.dashboard"))

            # Если роль неизвестна, возвращаем ошибку
            flash(f"Роль {user.role.name} не распознана. Обратитесь к администратору.", "danger")
            return redirect(url_for("user.login"))
        else:
            flash(f"Ошибка входа для пользователя {user.name}. Пожалуйста, проверьте логин и пароль!", "danger")
    return render_template("user/login.html", form=form)


@user.route("/user/logout", methods=["POST", "GET"])
def logout():
    logout_user()
    return redirect(url_for("user.login"))

app/templates/main/_flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/main/_footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
  </footer>

app/templates/main/_header.html
<div class="page">
  <aside class="sidebar">
    <div class="sidebar-header">
      <a href="{{ url_for('post.all') }}" class="sidebar-logo">
        <svg width="106" height="24" viewBox="0 0 106 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <!-- SVG path -->
        </svg>
      </a>
    </div>
    <nav class="sidebar-nav">
      <ul>
        <li><a href="{{ url_for('post.all') }}">Дом</a></li>
        {% if current_user.is_authenticated and current_user.role.name == "teacher" %}
        <li><a href="{{ url_for('post.create') }}">Добавить тему</a></li>
        {% endif %}
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('user.profile', user_id=current_user.id) }}">Учетная запись</a></li>
        {% endif %}
      </ul>
    </nav>
    <div class="sidebar-footer">
      {% if current_user.is_authenticated %}
      <span>Добро пожаловать, {{ current_user.login }}</span>
      <a href="{{ url_for('user.logout') }}" class="btn btn-outline-light">Выйти</a>
      {% else %}
      <a href="{{ url_for('user.login') }}" class="btn btn-outline-light">Войти</a>
      <a href="{{ url_for('user.register') }}" class="btn btn-warning">Регистрация</a>
      {% endif %}
    </div>
  </aside>

  <main>
    <div class="content">
      <!-- Здесь будет основной контент -->
    </div>
  </main>
</div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block style %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'main/_header.html' %}
    <div class="page">
      <main class="content">
        {% include 'main/_flash.html' %}
        <h1>{{ self.title() }}</h1>
        {% block content %}{% endblock %}
      </main>
      {% include 'main/_footer.html' %}
    </div>

    <script src="{{ url_for('static', filename='js/libs/bootstrap min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  {% block script %}{% endblock %}
  </body>
</html>